title: The World At My Finger Tips # your name (or website title) here
logo: "/images/circle-cropped%20(1).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Contact me: megan_ng@hotmail.com
  <br>
  <a href="https://www.linkedin.com/in/megan-ng-7708a74/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
