title: A Data Analytics Enthusiast # your name (or website title) here
logo: "images/just_me_circled.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://theworldatmyfingertips.github.io/">View My Projects Portfolio</a> 
  <a href=""https://theworldatmyfingertips.github.io/my_articles.md/">View My Articles</a> 
  <br>
  <a href="https://www.linkedin.com/in/megan-ng-7708a74/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
